Repository ember-tooling/ember-language-server, pull requests merged in 2018-04, with the labels that each got.

#106 Basic integration testing
  package.json
  test/fixtures/full-project/.editorconfig
  test/fixtures/full-project/.ember-cli
  test/fixtures/full-project/.eslintrc.js
  test/fixtures/full-project/.gitignore
  test/fixtures/full-project/.travis.yml
  test/fixtures/full-project/.watchmanconfig
  test/fixtures/full-project/README.md
  test/fixtures/full-project/app/app.js
  test/fixtures/full-project/app/components/.gitkeep
  test/fixtures/full-project/app/components/my-awesome-component.js
  test/fixtures/full-project/app/controllers/.gitkeep
  test/fixtures/full-project/app/helpers/.gitkeep
  test/fixtures/full-project/app/index.html
  test/fixtures/full-project/app/models/.gitkeep
  test/fixtures/full-project/app/resolver.js
  test/fixtures/full-project/app/router.js
  test/fixtures/full-project/app/routes/.gitkeep
  test/fixtures/full-project/app/styles/app.css
  test/fixtures/full-project/app/templates/application.hbs
  test/fixtures/full-project/app/templates/components/.gitkeep
  test/fixtures/full-project/app/templates/components/another-awesome-component.hbs
  test/fixtures/full-project/config/environment.js
  test/fixtures/full-project/config/targets.js
  test/fixtures/full-project/ember-cli-build.js
  test/fixtures/full-project/package.json
  test/fixtures/full-project/public/robots.txt
  test/fixtures/full-project/testem.js
  test/fixtures/full-project/tests/helpers/.gitkeep
  test/fixtures/full-project/tests/index.html
  test/fixtures/full-project/tests/integration/.gitkeep
  test/fixtures/full-project/tests/test-helper.js
  test/fixtures/full-project/tests/unit/.gitkeep
  test/fixtures/full-project/vendor/.gitkeep
  test/integration-test.ts
  yarn.lock
Labels: internal

#107 Migrate tests to use Jest
  .travis.yml
  appveyor.yml
  jest.config.js
  package.json
  test/__snapshots__/integration-test.ts.snap
  test/chokidar-test.ts
  test/diagnostic-test.ts
  test/ember-helpers-test.ts
  test/estree-utils-test.ts
  test/file-extension-utils-test.ts
  test/file-index-test.ts
  test/file-info-test.ts
  test/integration-test.ts
  test/position-utils-test.ts
  test/range-utils-test.ts
  test/tslint.ts
  test/unique-by-test.ts
  test/utils/diagnostic-test.ts
  yarn.lock
Labels: internal

#108 Added integration tests for all features
  .travis.yml
  package.json
  test/__snapshots__/integration-test.ts.snap
  test/fixtures/full-project/app/helpers/some-helper.js
  test/fixtures/full-project/app/models/model-a.js
  test/fixtures/full-project/app/models/model-b.js
  test/fixtures/full-project/app/router.js
  test/fixtures/full-project/app/routes/test-route.js
  test/fixtures/full-project/app/templates/definition.hbs
  test/fixtures/full-project/app/templates/test-route.hbs
  test/fixtures/full-project/app/transforms/custom-transform.js
  test/fixtures/full-project/tests/unit/models/model-a-test.js
  test/fixtures/full-project/tests/unit/models/model-b-test.js
  test/fixtures/full-project/tests/unit/routes/test-route-test.js
  test/fixtures/full-project/tests/unit/transforms/custom-transform-test.js
  test/integration-test.ts
Labels: internal

#111 Remove file index
  package.json
  src/completion-provider/template-completion-provider.ts
  src/definition-provider.ts
  src/file-index.ts
  src/file-info.ts
  src/project-roots.ts
  src/server.ts
  src/utils/chokidar.ts
  src/utils/deferred.ts
  test/__snapshots__/integration-test.ts.snap
  test/chokidar-test.ts
  test/file-index-test.ts
  test/file-info-test.ts
  test/integration-test.ts
  yarn.lock
Labels: enhancement

#113 Replace esprima with Babylon
  package.json
  src/definition-provider.ts
  src/symbols/js-document-symbol-provider.ts
  yarn.lock
Labels: internal

#115 Update to node 10 in .travis.yml
  .travis.yml
Labels: greenkeeper
